spring:
  datasource:
    url: jdbc:mysql://localhost:3306/permission
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
    port: 6379
server:
  port: 8080